### ISSUE TITLE
High resolution images

### ISSUE THREAD

**Issue by codonna9** [xinyu1205/recognize-anything#131]
Thank you very much for releasing the paper, code and the models. The zero shot ability of the Ram-family models is very good. However, I found that, due to the limitation of Swin v1, the models can only work with images of 224 or 384, while, in many real-world tasks, we need to work with high resolution images like 2k or 4k. Do you plan to add the ability to work with high resolution images in the future? 
I'd love to contribute but currently, I don't have GPUs which are powerful enough to train models.

**Comment by xinyu1205** [comment]
Hello, thank you for your attention. Capable on high-resolution images is indeed a promising work! 
However, due to my busy schedule, I am unable to complete it in the near future.
On the other hand, this should only require increasing resolution during the finetune stage and not consume too much GPU consumptions.

**Comment by codonna9** [comment]
Thanks a lot for your reply. I'll try that.
